services:
  - type: web
    name: vahansetu
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn --chdir vahansetu app:app --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 120
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0
